# Generated by Django 5.2.1 on 2025-05-31 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_cartitem_unique_together_cartitem_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', True)), fields=('user', 'product'), name='unique_active_cart_per_product'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
